apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-dev.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "test-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "test-dev.selectorLabels" . | nindent 4 }}
